### ISSUE TITLE
Everything doesn't work again

### ISSUE THREAD

**Issue by esotericDisciple** [cloudrac3r/bibliogram#102]
`◸―――――――――――――――――――――――――――――――――――――◹ ···< | 500. That's an error. | >··· ◺―――――――――――――――――――――――――――――――――――――◿ ╱ Are you visiting this website? Not sure what's going on? ╲ ╲ You might want to come back later. ╱ TypeError: Cannot read property 'json' of undefined at /home/cloud/bupdate/bibliogram/src/lib/collectors.js:284:18 at runMicrotasks () at processTicksAndRejections (internal/process/task_queues.js:97:5) at async Timeline.fetchUpToPage (/home/cloud/bupdate/bibliogram/src/lib/structures/Timeline.js:58:19) at async Object.code (/home/cloud/bupdate/bibliogram/src/site/api/routes.js:202:24)`

**Comment by cloudrac3r** [comment]
We know. https://matrix.to/#/#bibliogram:matrix.org

**Comment by esotericDisciple** [comment]
I can't open the url
