### ISSUE TITLE
Custom 404 only supported by endpoints

### ISSUE THREAD

**Issue by TheFrenchGhosty** [cloudrac3r/bibliogram#14]
The "custom" 404 page is only supported by the endpoints (https://github.com/cloudrac3r/bibliogram#user-facing-endpoints), and for example https://bibliogram.art/test just show the default 404 message.

**Comment by cloudrac3r** [comment]
This was fixed 8 days ago in 9d86bdbc7492f1616ee9764334641634fa1b9b74. Hurrah!
