### ISSUE TITLE
Mark verified accounts as verified

### ISSUE THREAD

**Issue by Perflyst** [cloudrac3r/bibliogram#16]
Currently bibliogram does not indicate if a profile is verified or not, would be nice to have

**Comment by mendel5** [comment]
I've created a layout for how the verification status can be displayed on the profile page. The account that was used is https://bibliogram.art/u/instagram .

Bibliogram profile info before (without "verified"):
![bibliogram_verified_before](https://user-images.githubusercontent.com/60322520/79635965-a0ab6d00-8174-11ea-8d96-58c485974e01.png)

Bibliogram profile info after (with "verified"):
![bibliogram_verified_after](https://user-images.githubusercontent.com/60322520/79635970-a4d78a80-8174-11ea-82d7-834aa7c0a683.png)

**Comment by cloudrac3r** [comment]
What about a "blue check" like Instagram actually uses? Doesn't have to be the exact same icon, but similar symbolism would be ideal, I think.

**Comment by mendel5** [comment]
A blue check mark like on Instagram.com would also be possible.

I took inspiration for the "Verified? Yes/ No" from [Invidious](https://github.com/omarroth/invidious/). If you watch a video Invidious, e.g. [this one](https://invidio.us/watch?v=x47Ins_rkgk), it shows: "Family friendly? Yes".

Invidious video info: Family friendly? Yes
![invidious_family-friendly](https://user-images.githubusercontent.com/60322520/79643474-65746280-81a3-11ea-9b6c-15745f3c97ac.png)

On issue https://github.com/cloudrac3r/bibliogram/issues/27 you mentioned web accessibility. I think the text option with yes/no is more straightforward than the blue check mark. The meaning of the blue check mark is more ambiguous to users who are not familiar with Instagram.

**Comment by cloudrac3r** [comment]
I was hoping someone would want to dive into this and try to implement it themselves, but that didn't happen, so I did it myself in 5fc765d8cb97027cf9204180b86e242e085cb2d5.

**Comment by mendel5** [comment]
@cloudrac3r Thank you!
