### ISSUE TITLE
Use sharp for image resizing

### ISSUE THREAD

**Issue by cloudrac3r** [cloudrac3r/bibliogram#18]
[Sharp](https://www.npmjs.com/package/sharp) is faster than GraphicsMagick and does not depend on a system package. Investigate switching to it.

**Comment by Booteille** [comment]
I am curious about performances gains on this. Did you benchmark it?

**Comment by cloudrac3r** [comment]
I did not benchmark it myself, but sharp provides its own benchmarks:

> Resizing an image is typically 4x-5x faster than using the quickest ImageMagick and GraphicsMagick settings due to its use of libvips. [[quote source]](https://www.npmjs.com/package/sharp)

Actual benchmark details: https://sharp.pixelplumbing.com/performance

Even if there were no performance gains from sharp, it is still an improvement since it no longer requires GraphicsMagick to be installed on the system.

**Comment by Booteille** [comment]
> Even if there were no performance gains from sharp, it is still an improvement since it no longer requires GraphicsMagick to be installed on the system.

True!

And I saw their description but I wanted to know if you personally noticed performances improvements. So you answered to me! Thanks!
