### ISSUE TITLE
Avoid 429 rate limits

### ISSUE THREAD

**Issue by cloudrac3r** [cloudrac3r/bibliogram#19]
Relevant code is around here and I have no idea what's going on. Rate limits are not documented anywhere. Instaloader has CI for rates. I'm glad I don't have to figure this out myself. https://github.com/instaloader/instaloader/blob/302145f54fbfb08944333e456d02c13b6b94f3a0/instaloader/instaloadercontext.py#L306

**Comment by cloudrac3r** [comment]
Update for future me:

- Each query_hash is ratelimited separately
- Each hash gets 200 requests per 11 minutes
- Each request will individually fall out the back in its own time, rather than the entire group refreshing at once
- If all 200 requests are used and another is queued, wait an additional 6 seconds after a slot becomes available

**Comment by unixfox** [comment]
Is Instagram throwing a CAPTCHA on the 429 page?
I read in the source code that it requires logging in but is it the only possible way to get unblocked?

**Comment by cloudrac3r** [comment]
It seems to just 302 redirect to /accounts/login, but now that my server is actually blocked I could investigate a little more.

**Comment by cloudrac3r** [comment]
For me, when I am redirected to the login page, it includes this inside the _sharedData object:

    captcha: { enabled: false, key: '' },

I think this means that in some situations a captcha will actually be required to sign up or log in, perhaps if there have been many failed password attempts.

I cannot find captcha data that implies it will unblock the instance if it is solved, but you're welcome to look for yourself!

cc @unixfox
