### ISSUE TITLE
The name is a blasphemy, would you consider changing it?

### ISSUE THREAD

**Issue by DontUseGithub** [cloudrac3r/bibliogram#20]

**Comment by cloudrac3r** [comment]
[citation needed.]

**Comment by DontUseGithub** [comment]
Are you saying that the title isn't trying to make a reference to the Bible?

**Comment by cloudrac3r** [comment]
No. No it's not. Biblio is an English prefix from the Greek *biblion,* meaning book. It can be combined into words like *bibliophile* (meaning book-lover) or *bibliogram*. Yes, bibliogram is a word. I don't understand what it means, but it is a word. https://en.m.wikipedia.org/wiki/Bibliogram

The name was not intentionally designed to reference any religion, or any religious books, or any religious teachings.

Please let me know if you have any further concerns.

**Comment by DontUseGithub** [comment]
My bad, sorry :innocent:
Now I'm thinking, the root of _Biblio_ could also be _**biblio**graphy_ which would make more sense than _Bible_.

Thanks for taking the time to reply here and have a great day!
