### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by Perflyst** [cloudrac3r/bibliogram#21]
Since bibliogram now stores data in a database a privacy policy should be added

**Comment by cloudrac3r** [comment]
Since settings are available for this and further request logging could be configured through a reverse proxy like nginx I think each instance owner should write their own. Perhaps I could create a template, though.

**Comment by cloudrac3r** [comment]
Okay, the current plans are:

1. Make a template privacy policy and commit it
1. Ask the instance owner to copy the file to a new location and then edit it at will.
1. Add a config option. When enabled, the copied file will be loaded and linked to on the homepage and various /api/stats keys will be set.

Let me know if you have issues with this plan.

**Comment by cloudrac3r** [comment]
Privacy policy template added in 8b964a18e4ca0bcab930b98eb07481b0d4be63f9.

**Comment by cloudrac3r** [comment]
Added stats feature in 4c83a7804a684740eb64feb64e28689838464328.
