### ISSUE TITLE
Invidious / Nitter auto rewrite

### ISSUE THREAD

**Issue by Perflyst** [cloudrac3r/bibliogram#22]
Would be nice if Bibliogram could auto re-write youtube and twitter links to invidious and nitter

**Comment by cloudrac3r** [comment]
It would be good to have #28 before this, but not essential.

**Comment by narFnarF** [comment]
@Perflyst In the meantime, you might want to look into a browser extension like this one: https://github.com/SimonBrazell/privacy-redirect
I use it myself and it's quite good!

**Comment by Perflyst** [comment]
@narFnarF Thank you, but Invidition is better since it also replaces embeds etc. I do not want this feature for myself but for other people which are maybe not aware of Nitter / Invidious.

OT: For general redirects / request modifications I recommend https://addons.mozilla.org/en-US/firefox/addon/requestcontrol/

**Comment by cloudrac3r** [comment]
Links are only allowed in the link field of profile bios, which means that each user only gets one link ever. If you can find profiles that have YouTube or Twitter links that I can use as test cases, please post them in the comments here.

- Example: YouTube channel link: https://bibliogram.art/u/skycorphomevideo (content warning: loss of control/acting physical violence)

**Comment by cloudrac3r** [comment]
The settings page exists now, so this can be worked on at some point, but it's pretty low priority since each Instagram user only gets one link ever.

**Comment by cloudrac3r** [comment]
Demo pages: [YouTube](https://bibliogram.art/u/skycorphomevideo/) / [Twitter](https://bibliogram.art/u/twitter/)

The domain is replaced and the rest of the URL is untouched. This should give good-enough compatibility without making the code or interface overly complex.
