### ISSUE TITLE
Hashtags are not clickable

### ISSUE THREAD

**Issue by stemy2** [cloudrac3r/bibliogram#24]
Hello,

It would be nice if the hashtags were clickable.

**Comment by cloudrac3r** [comment]
What would clicking them do?

**Comment by Perflyst** [comment]
It probably should go to https://www.instagram.com/explore/tags/test once implemented

**Comment by cloudrac3r** [comment]
"once implemented" is the key part here :)

once the tag explore page exists, this issue will be fixed.

**Comment by cloudrac3r** [comment]
I believe viewing hashtags is part of #38, so I'll close this as a duplicate.
