### ISSUE TITLE
When import RSS feed from bibliogram in Feedly, the link to the post always points to the same github URL

### ISSUE THREAD

**Issue by narFnarF** [cloudrac3r/bibliogram#31]
When import RSS feed from bibliogram in Feedly, the link to the website always points to the instance's url instead of to the profile page of the specific user.

From what I can guess, it looks to be the `rss.channel.link` and `rss.channel.image.link` fields
The incorrect URL: https://bibliogram.example.com
The expected URL would be, I'm guessing, `https://bibliogram.example.com/u/maruti_bitamin`

**Comment by cloudrac3r** [comment]
What instance are you requesting the feed from? If it is your own, what have you set in `/config.js:website_origin`?

**Comment by narFnarF** [comment]
Ah, yes, I missed that part of the install process! Sorry!

Having made that change, I see all the "undefined" and the "http://localhost:10407" gone. So that's great.

However, my original issue is still occurring:
Both `rss.channel.link` and `rss.channel.image.link` still point to `https://bibliogram.example.com` instead of `https://bibliogram.example.com/u/maruti_bitamin`

**Comment by cloudrac3r** [comment]
Does updating to commit a668547735558c536d2639b1f5a05cbcadf01e2c change anything?

**Comment by narFnarF** [comment]
I don't know how to update to a specific commit, so I did the following:
```
git fetch
git pull
npm install --no-optional
pm2 restart bibliogram #That's the equivalent of doing "npm start"
```
And now the RSS feeds' link fields works properly!
Thanks!
