### ISSUE TITLE
[Feature request] Swiping

### ISSUE THREAD

**Issue by stemy2** [cloudrac3r/bibliogram#32]
Hello,

Some instagram posts require swiping to see all photos. Since there's no swipe functionality in bibliogram, it's impossible to see these photos outside instagram.

**Comment by cloudrac3r** [comment]
Galleries on Bibliogram scroll vertically. Swipe upwards on a phone, or use the mouse wheel while hovering the pictures on computer.

I plan to add more view options, possibly including a horizontal mode akin to Instagram, in the future.

**Comment by cloudrac3r** [comment]
Samples:

https://bibliogram.art/p/B8jmH_tAZKC
https://bibliogram.art/p/B8ZQNLJgK_x
https://bibliogram.art/p/B6QTwhLguK0

**Comment by cloudrac3r** [comment]
Re-open if you have further problems relating to this.
