### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by ahangarha** [cloudrac3r/bibliogram#33]
Hi

I think this app needs RTL support. Since the content can be RTL and LTR, it needs to support bidi (bidirectional) text.

You may assign it to me and I add it ASAP

**Comment by cloudrac3r** [comment]
Thank you! Please open a pull request when you're done.

**Comment by cloudrac3r** [comment]
Closed in a14633ef9247b641945d083e0bb634029929246a by #37.
