### ISSUE TITLE
multiple users in a single url

### ISSUE THREAD

**Issue by treble2019** [cloudrac3r/bibliogram#36]
Thanks for this wonderful software.

Would it be possible to implement something like multiple users in one URL.

Example:
https://bibliogram.snopyta.org/therock,cristiano,arianagrande

Reason:
For example nitter does this like this (not my actual choice of twitter people!!!):
https://nitter.snopyta.org/katyperry,rihanna,Cristiano

or

https://nitter.net/NASA/lists/Astronauts

Please see:
https://github.com/zedeus/nitter/issues/83

**Comment by cloudrac3r** [comment]
This could end up consuming an excessive amount of the rate limit to Instagram.

This will likely be added when a main subscription page is added, and the subscription page will not be added until after rate limits to Bibliogram itself are added.

I like the suggestion though!

For now you can use RSS feeds.
