### ISSUE TITLE
Updater page always uses "npm install"

### ISSUE THREAD

**Issue by TheFrenchGhosty** [cloudrac3r/bibliogram#39]
In the updater page, "You must run ```npm install``` after pulling" is displayed even if Tor isn't enabled in the instance.

It would be nice if it could instead display "You must run ```npm install --no-optional``` after pulling" if it detect that Tor isn't enabled.

Screenshot (of https://bibliogram.pussthecat.org/, instance where Tor isn't enabled):

![bibliogram](https://user-images.githubusercontent.com/47571719/76789680-35f1c500-67b5-11ea-8d85-20e7932530ca.png)

**Comment by cloudrac3r** [comment]
Good idea.

**Comment by cloudrac3r** [comment]
Updater page was removed in a7a9af8854aa3c2b727e0a6bbea7d991dff774dd because I had no way to test it and because I don't think anyone used it.
