### ISSUE TITLE
/u/admin always trigger a 503

### ISSUE THREAD

**Issue by TheFrenchGhosty** [cloudrac3r/bibliogram#40]
If a user go to /u/admin a 503 will be triggered, and the homepage of the instance will mark itself as blocked.

Gif of the issue:

![bibliogram](https://user-images.githubusercontent.com/47571719/76790478-d3012d80-67b6-11ea-86cf-cd8e6cef0fc1.gif)

**Comment by cloudrac3r** [comment]
Nice find.

**Comment by cloudrac3r** [comment]
Should be fixed in 41cbffa95a7e06e1454ec9776e781724cf049775.
