### ISSUE TITLE
Error: integer@2.1.0 install: node-gyp rebuild

### ISSUE THREAD

**Issue by kalak-sudo** [cloudrac3r/bibliogram#42]
Hi everyone! 

I get this error on a fresh install, debian 10, nodejs 12.16.1 

I install nodejs 12.x following the [official guide](https://github.com/nodesource/distributions/blob/master/README.md#debinstall) and then follow the steps shown on the [front page](https://github.com/cloudrac3r/bibliogram#installing).

Then, I get this error right after typing `npm install --no-optional`:

> 
> 12123 warn optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
> 12124 warn notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 12125 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid OS:    darwin
> 12125 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Valid Arch:  any
> 12125 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual OS:   linux
> 12125 verbose notsup SKIPPING OPTIONAL DEPENDENCY: Actual Arch: x64
> 12126 verbose stack Error: integer@2.1.0 install: `node-gyp rebuild`
> 12126 verbose stack Exit status 1
> 12126 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 12126 verbose stack     at EventEmitter.emit (events.js:311:20)
> 12126 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 12126 verbose stack     at ChildProcess.emit (events.js:311:20)
> 12126 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 12126 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 12127 verbose pkgid integer@2.1.0
> 12128 verbose cwd /root/bibliogram
> 12129 verbose Linux 4.19.0-8-amd64
> 12130 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "--no-optional"
> 12131 verbose node v12.16.1
> 12132 verbose npm  v6.13.4
> 12133 error code ELIFECYCLE
> 12134 error errno 1
> 12135 error integer@2.1.0 install: `node-gyp rebuild`
> 12135 error Exit status 1
> 12136 error Failed at the integer@2.1.0 install script.
> 12136 error This is probably not a problem with npm. There is likely additional logging output above.
> 12137 verbose exit [ 1, true ]
> 
>

**Comment by cloudrac3r** [comment]
I think you haven't included some output here.

How much memory (RAM) and swap is available on the computer that you're installing on?

**Comment by kalak-sudo** [comment]
I have 1.5GB free MEM and 1GB swap free.

Also 10GB hdd free space.

Here is another log:

> integer@2.1.0 install /root/bibliogram/node_modules/integer
> node-gyp rebuild

> Traceback (most recent call last):
>   File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py", line 47, in <module>
>     import gyp
>   File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 10, in <module>
>     import gyp.input
>   File "/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 7, in <module>
>     import ast
> ImportError: No module named ast
> gyp ERR! configure error 
> gyp ERR! stack Error: `gyp` failed with exit code: 1
> gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
> gyp ERR! stack     at ChildProcess.emit (events.js:311:20)
> gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
> gyp ERR! System Linux 4.19.0-8-amd64
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /root/bibliogram/node_modules/integer
> gyp ERR! node -v v12.16.1
> gyp ERR! node-gyp -v v5.0.5
> gyp ERR! not ok 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! integer@2.1.0 install: `node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the integer@2.1.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-03-20T17_34_51_795Z-debug.log
>

**Comment by cloudrac3r** [comment]
Please see if anything in this thread helps you. https://github.com/lovell/sharp/issues/1087#issuecomment-359582561

**Comment by kalak-sudo** [comment]
Thanks @cloudrac3r :)

I read that comment, and as suggested, after running

`apt-get install python-dev`

It installs **perfectly** everything, but when I run:

`npm run start`

I get the following **error**:

> bibliogram@1.0.0 start /root/bibliogram
> cd src/site && node server.js

> 
> internal/fs/utils.js:230
>     throw err;
>     ^
> 
> Error: ENOENT: no such file or directory, scandir '/root/bibliogram/node_modules/node-sass/vendor'
>     at Object.readdirSync (fs.js:871:3)
>     at Object.getInstalledBinaries (/root/bibliogram/node_modules/node-sass/lib/extensions.js:132:13)
>     at foundBinariesList (/root/bibliogram/node_modules/node-sass/lib/errors.js:20:15)
>     at foundBinaries (/root/bibliogram/node_modules/node-sass/lib/errors.js:15:5)
>     at Object.module.exports.missingBinary (/root/bibliogram/node_modules/node-sass/lib/errors.js:45:5)
>     at module.exports (/root/bibliogram/node_modules/node-sass/lib/binding.js:15:30)
>     at Object.<anonymous> (/root/bibliogram/node_modules/node-sass/lib/index.js:14:35)
>     at Module._compile (internal/modules/cjs/loader.js:1158:30)
>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
>     at Module.load (internal/modules/cjs/loader.js:1002:32) {
>   errno: -2,
>   syscall: 'scandir',
>   code: 'ENOENT',
>   path: '/root/bibliogram/node_modules/node-sass/vendor'
> }
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! bibliogram@1.0.0 start: `cd src/site && node server.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the bibliogram@1.0.0 start script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-03-21T09_15_51_341Z-debug.log

And here is the log:

> 
> 0 info it worked if it ends with ok
> 1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'start' ]
> 2 info using npm@6.13.4
> 3 info using node@v12.16.1
> 4 verbose run-script [ 'prestart', 'start', 'poststart' ]
> 5 info lifecycle bibliogram@1.0.0~prestart: bibliogram@1.0.0
> 6 info lifecycle bibliogram@1.0.0~start: bibliogram@1.0.0
> 7 verbose lifecycle bibliogram@1.0.0~start: unsafe-perm in lifecycle true
> 8 verbose lifecycle bibliogram@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/bibliogram/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
> 9 verbose lifecycle bibliogram@1.0.0~start: CWD: /root/bibliogram
> 10 silly lifecycle bibliogram@1.0.0~start: Args: [ '-c', 'cd src/site && node server.js' ]
> 11 silly lifecycle bibliogram@1.0.0~start: Returned: code: 1  signal: null
> 12 info lifecycle bibliogram@1.0.0~start: Failed to exec start script
> 13 verbose stack Error: bibliogram@1.0.0 start: `cd src/site && node server.js`
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:311:20)
> 13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:311:20)
> 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
> 14 verbose pkgid bibliogram@1.0.0
> 15 verbose cwd /root/bibliogram
> 16 verbose Linux 4.19.0-8-amd64
> 17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "start"
> 18 verbose node v12.16.1
> 19 verbose npm  v6.13.4
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error bibliogram@1.0.0 start: `cd src/site && node server.js`
> 22 error Exit status 1
> 23 error Failed at the bibliogram@1.0.0 start script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by cloudrac3r** [comment]
Don't run as root!! D:

Create a new ordinary user on the server and use that to run Bibliogram. You do _not_ need root or sudo for any part of Bibliogram, except when using `apt`.

**Comment by kalak-sudo** [comment]
Yes, solved it using another user (not as root) :)

Here is a summary with solution:

1) install nodejs 12.x following the [official guide](https://github.com/nodesource/distributions/blob/master/README.md#debinstall)

2) Installed `apt-get install python-dev`

3) Follow the steps shown on the [front page](https://github.com/cloudrac3r/bibliogram#installing) using another user (not as root).

PD: I think that step number 3 should be added on the front page, with all the installation steps, as I am sure this only happened to me.

Thanks @cloudrac3r :)

**Comment by cloudrac3r** [comment]
I've added these to the troubleshooting page :) https://github.com/cloudrac3r/bibliogram/wiki/Troubleshooting
