### ISSUE TITLE
redirect user

### ISSUE THREAD

**Issue by mehkera** [cloudrac3r/bibliogram#43]
Would be nice to redirect : 
https://bibliogram.snopyta.org/paillettes_et_imagination/ to
https://bibliogram.snopyta.org/u/paillettes_et_imagination/

instead we have 404

**Comment by cloudrac3r** [comment]
Enjoy.

**Comment by Perflyst** [comment]
enjoy the 500 instead of the 404 :P

**Comment by cloudrac3r** [comment]
idk how to inform you that you need to run npm install but I did in fact create /admin/updater to help you avoid situations like this

run npm install
