### ISSUE TITLE
Changing default port, config.js ignored?

### ISSUE THREAD

**Issue by EchoDev** [cloudrac3r/bibliogram#44]
I have been trying to change the default port but for some reason the config.js seems to be ignored

I tried the following options in config.js

```
module.exports = {
    website_origin: "http://localhost:12345"
}
```

```
module.exports = {
    website_origin: "http://localhost:12345",
}
```

```
module.exports = {
    website_origin: "http://127.0.0.1:12345"
}
```
```
module.exports = {
    website_origin: "http://127.0.0.1:12345",
}
```

Bibliogram stays on the default port with all these options.
Am I reading this option wrong? Am I using the wrong setting?

**Comment by cloudrac3r** [comment]
You are using the wrong option.

Right now there isn't an easy way to change the port. Hold on tight while I add a setting for it.

**Comment by cloudrac3r** [comment]
I've updated `constants.js`, please look at the comments in the first part which should explain everything. Comment here if you get stuck.

**Comment by EchoDev** [comment]
I got it working on a different port now. Thanks for the quick fix!
