### ISSUE TITLE
Asking really nicely: Display comments on a post

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#45]
**Description**
In the README.md file you wrote:
"These features will not be added, unless you ask reallllly nicely: Comments [...]"

I wanted to ask really nicely if you can add support for displaying comments on a post.

**Example**
- Michael from Vsauce on Instagram.com https://www.instagram.com/p/BuabuvQAU4r/ : Comments are displayed
- Michael from Vsauce on Bibliogram.art https://bibliogram.art/p/BuabuvQAU4r/ : Comments are not displayed

**Comment by cloudrac3r** [comment]
Your desires have been noted. Viewing comments as a feature is tracked in #25, subscribe to that thread or make a post in it if you have feedback or want to join the discussion. o7

**Comment by cloudrac3r** [comment]
I'll close this as a duplicate of #25. If you have any other comments, please leave them there :)
