### ISSUE TITLE
Add ip in pinski configuration

### ISSUE THREAD

**Issue by uselesspseudo** [cloudrac3r/bibliogram#48]
Is it possible to add the line to configure the ip the server will listen to ?

const pinski = new Pinski({                                                                           
        port: +process.env.PORT || constants.port,                                                    
        ip: "localhost",                                                                              
        relativeRoot: __dirname,                                                                      
        basicCacheControl: {                                                                          
                exts: ["ttf", "woff2", "png", "jpg", "jpeg", "svg", "gif", "webmanifest", "ico"],     
                seconds: 604800                                                                       
        },                                                                                            
})                                                                                 

I want to host bibliogram under an ipv6 address and without this I couldn't.

**Comment by cloudrac3r** [comment]
To listen on IPv6 you need to provide the string `::` as the address to listen on.

However, I recommend using the default in Bibliogram, and configuring nginx to listen on IPv6 and proxy_pass requests to Bibliogram. See https://github.com/cloudrac3r/bibliogram/wiki/Installing#configuring-https.

    listen [::]:80 default_server; 
    listen [::]:443 ssl http2 default_server;

I hope I understood your request correctly.

**Comment by uselesspseudo** [comment]
Oh you are totally right I thought I couldn't redirect an ipv6 to an ipv4 but I can.

Don't you think it may be interesting to allow the choice to listening another address than 0.0.0.0.

**Comment by cloudrac3r** [comment]
I added a config option for you.
