### ISSUE TITLE
Images return 403 if instance runs a few days

### ISSUE THREAD

**Issue by Perflyst** [cloudrac3r/bibliogram#5]
Some images return a 403 error (probably the instagram url changes or something) if they have been viewed a few days ago and then re-viewed again without restarting the instance between these days.

Example image: https://bibliogram.snopyta.org/p/B7bd1APhTU4

If the instance gets restarted the images work again

**Comment by cloudrac3r** [comment]
This is interesting. I shall find out how long it takes for a URL to expire and set the cache time accordingly.

This also means that there is a problem with the current cache system — the shortcode cache is supposed to have a TTL of 30 minutes. I guess I have some bugs.

Thank you for this information.

**Comment by cloudrac3r** [comment]
I have made corrections to the caching code and you shouldn't encounter this issue anymore. Image URLs will still expire in the same way as before, but the cache should discard them well before that time.
