### ISSUE TITLE
Layout of post page: Swap positions of image and description/comment section

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#51]
**Description**
When you open a post on Instagram.com, an overlay opens. The image is on the left side and the description/comment section is on the right side.

When you open a post on Bibliogram, the overlay opens as well. However the description/comment section is on the left side and the image is on the right side.

**Proposal**
To make Bibliogram feel more familiar to users and make the transition easier, the layout of Bibliogram's post page should be like the one of Instagram.

**Images for visualization:** 
![instagram](https://user-images.githubusercontent.com/60322520/79566011-169ad000-80b2-11ea-8458-ad1a13109d3b.png)
![bibliogram](https://user-images.githubusercontent.com/60322520/79566018-1995c080-80b2-11ea-9630-7377ce016184.png)

**Example**
* Instagram.com: [Profile](https://www.instagram.com/testaccountorch/) and [post](https://www.instagram.com/p/BYIvuVsnU5m/) with image left, comments right
* Bibliogram: [Profile](https://bibliogram.art/u/testaccountorch/) and [post](https://bibliogram.art/p/BYIvuVsnU5m/) with comments left, image right

**Comment by cloudrac3r** [comment]
Interesting idea. Thanks for the diagrams. Personally I like the caption on the left, so we'll wait on #28 first.

**Comment by mendel5** [comment]
Hi Cadence, I read your comment just now. I have created a pull request which should implement the proposed layout change.

**Comment by cloudrac3r** [comment]
The settings page exists and there's a template for this particular setting already. You can have a stab at implementing it now if you want. All you have to do is enable the control by setting `true` to `false` on the correct control in `settings.pug`, then add a class somewhere using pug, then edit the sass to change the element order based on that class. Or you could change the order of the elements physically in Pug, that works too. Have a go!

**Comment by cloudrac3r** [comment]
This has been untouched for 2 weeks, so I went ahead and did it myself.

**Comment by mendel5** [comment]
Thank you!
