### ISSUE TITLE
Profile picture not shown on profile page when recently changed

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#56]
Transferred from https://github.com/cloudrac3r/bibliogram/issues/55 .

Profile pictures that were not shown:
* https://bibliogram.art/u/neymarjr but works on https://www.instagram.com/neymarjr/
* https://bibliogram.art/u/justinbieber but works on https://www.instagram.com/justinbieber/

Now they are displayed.

**Comment by cloudrac3r** [comment]
For the sake of threading,

> This happens when somebody changes their profile picture because the old URL is then invalid but still cached in Bibliogram. I'm trying to make this automatically refresh, but it seems that it doesn't work properly until a cache cycle. 2 hours later, the profiles that you linked have been through a cache cycle and now have correct pictures.

**Comment by cloudrac3r** [comment]
Probably fixed by a45142a02d00f0771f04c1c59a13c406b4513d12
