### ISSUE TITLE
Add option to change the number of images per row on a profile page

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#59]
**Description**
Some people post a series of images on their Instagram.com feed that form a bigger picture. I'm not exactly sure what this is called. Some terms I found are "grid pattern", "split" and "3 part".

The standard behavior of Bibliogram is to fill the rows on a profile with images up to the entire page width. This is very nice and should definitely be kept in all future versions of Bibliogram. 

However the standard behavior of Instagram.com is to show three images per row on a profile. Therefore some of these patterns don't work out of the box in Bibliogram because there are more than three images on a row.

**Proposal**
Maybe an option can be added to the upcoming settings page (see https://github.com/cloudrac3r/bibliogram/issues/28 ) where it is possible to set two (or more) options for the number of images per row:
* 3 / Instagram.com standard
* full page width

**Example**
* [Profile](https://www.instagram.com/testaccountorch/) on Instagram.com with correct display of 9 part image series over 3 rows (3+3+3)
* [Profile](https://bibliogram.art/u/testaccountorch/) on Bibliogram.art where the 9 part series are incorrectly displayed on two rows (6+3)

**Comment by cloudrac3r** [comment]
Waiting on settings #28 (soon?)

**Comment by cloudrac3r** [comment]
No longer waiting!

**Comment by cloudrac3r** [comment]
Setting added in f6977ed3b950291c981d3ed8973aa13a4a96671e!

**Comment by mendel5** [comment]
Thanks!
