### ISSUE TITLE
Create a homepage

### ISSUE THREAD

**Issue by Booteille** [cloudrac3r/bibliogram#6]
Hi.

First, thanks for your work on this. That's great that, finally, someone is doing this.

I just noticed the homepage of https://bibliogram.snopyta.org/ is redirecting to a 404.
Maybe that would be great to have a homepage, something like what Nitter did?

**Comment by cloudrac3r** [comment]
Ah, someone noticed. :p

I do expect to add a homepage in the future, hopefully I can do this soon. You can see this task on the readme.

If you have suggestions for what things specifically you would like on the homepage, write them here! I just planned to have a logo/banner, a username input box, and a description of what the site is for.

I will leave this issue open until a homepage is actually added.

**Comment by Booteille** [comment]
Thanks!

I think it should be enough. Just, I would like to know which version of the software the server is using, maybe on the homepage or in an about page. (I don't really care where, just somewhere)
So, if you don't want to put it in the landing page, I can open a new issue for an about page.

Thanks again for your work!

**Comment by cloudrac3r** [comment]
Good plan. I think I'll make the front page be home and about in one place. There will also be an Invidious-like /api/v1/stats with relevant info. I want to get the stats endpoint out sooner rather than later.

**Comment by cloudrac3r** [comment]
Homepage added in 788aaea3d127dd4ebf36640128965c1c3a58ecfe. I'll leave this issue open to collect further ideas and improvements for a couple of days.
