### ISSUE TITLE
Cookie save or load endpoint

### ISSUE THREAD

**Issue by allendema** [cloudrac3r/bibliogram#60]
As the title says, we need an option to save or load prefered settings which could be deleted after quiting the browser.  🍪

**Comment by mendel5** [comment]
Related to " Add user settings page #28 "

**Comment by Num25r** [comment]
wouldn't something like cookie quick manager do this or am i miss understanding ?

**Comment by allendema** [comment]
@Num25r: The point is to make this work without relying on other services or extenstions.

**Comment by cloudrac3r** [comment]
Added in 0c16c027e96529b5fb1a11aeb6f34f661211ff4a!
