### ISSUE TITLE
Add "Back" button to Settings page to go back to profile page

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#63]
**Description**
This issue is about user interface and user experience (UI/ UX). To illustrate what I mean I will describe my work flow:

1. I start at https://bibliogram.art/ (or any other Bibliogram instance)
2. I enter the profile name in the "Go to profile" box and click "Go"
3. When I am on the profile, I see the "Settings" button at the bottom of the profile overview (left bar)
4. I click on the "Settings" link and get redirected to the Settings page
5. I change some settings, e.g. the theme
6. I click on "Home" and get redirected to the start page at https://bibliogram.art/

**Proposal**
As described in step 6 above, I get redirected to the start page. However I actually don't want to go there right now. Instead what Bibliogram needs is a "Back to profile" button that redirects me back the profile where I clicked on the "Settings" button. This way I can go back to the profile where I originally came from and can continue viewing the profile's content.

**Comment by mendel5** [comment]
I hope everyone understands what I meant here.

One option to get the link for the "Back to profile" button is to extract it from the "Referer" HTTP header.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Referer

However some users who are concerned about their privacy might have completely disabled the sending of HTTP referers in their browser, so this option wouldn't work for them. Maybe there is another way to do it...

**Comment by cloudrac3r** [comment]
Yeah. This is a good idea and the current behaviour annoys me as well.

I am aware that I cannot use the Referer header. Invidious does it by adding a `referer=...` query parameter. I think I'll do something like this.

**Comment by cloudrac3r** [comment]
Completed in 474274740ffac7bddb43478c7e653bc1d300ef0a, thank you for the suggestion!

**Comment by mendel5** [comment]
Works very well, thank you!
