### ISSUE TITLE
Rename themes to more descriptive names

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#64]
**Description**
Currently there are two themes with these names:
* Classic
* Classic blue

**Proposal**
The names of the themes could be more descriptive and intuitive.

The classic theme might have been the first theme that existed, however when you read the name "classic" you don't know what the theme will look like. The name should describe the look and color of each theme. Therefore the name "classic blue" is a step in the right direction when compared to just "classic".

Maybe we can go a step further and include a unique name in the theme. How about renaming the themes like this:
* Classic  →  Cadence vanilla
* Classic blue  →  Cobalt blue

**Comment by cloudrac3r** [comment]
Fair enough. How about:

- Classic → Vanilla sard
- Classic blue → Aerial blue

**Comment by cloudrac3r** [comment]
Although since classic blue is very similar to classic, perhaps I should name them both variations on "vanilla".

**Comment by mendel5** [comment]
> Although since classic blue is very similar to classic, perhaps I should name them both variations on "vanilla".

Yes, that's a good idea.

I would strongly advocate that at least the "Classic" theme has your name in it! Maybe one of these:
* Cadence vanilla
* Cadence's vanilla
* Cloudrac3r's vanilla
* Cloudracer's vanilla

**Comment by mendel5** [comment]
> Although since classic blue is very similar to classic, perhaps I should name them both variations on "vanilla".

Yes, that's a good idea.

I would strongly advocate that at least the "Classic" theme has your name in it! Maybe one of these names:
* Cadence vanilla
* Cadence's vanilla
* Cloudrac3r's vanilla
* Cloudracer's vanilla

**Comment by cloudrac3r** [comment]
> I would strongly advocate that at least the "Classic" theme has your name in it!

Why?

After all, as you said,

> The name should describe the look and color of each theme.

Knowing my name doesn't tell people what the theme will look like. I don't expect custom theme authors to put their name as the display name either (though they can if they want to).

**Comment by mendel5** [comment]
You are right, my statements are contradictory.

Generally I think we should not name any themes after their creators. I read a little bit about naming things online and came across this question on Academia StackExchange:
[Why the taboo against naming discoveries after yourself?](https://academia.stackexchange.com/questions/34555/why-the-taboo-against-naming-discoveries-after-yourself)

One comment says that when something is named after its creator/ inventor, this conveys that "the most important thing about it is that he created it". But for a theme it's more important to know what the theme will look like than who originally created it. Therefore I advocated to rename the classic theme to something with "vanilla".

However the linked questions also says this: "Traditionally naming after scientists has been considered an honour bestowed upon somebody by their colleagues." I thought that you as a creator of Bibliogram should receive the honor to have a small part in it named after you.

But if one of the theme's carried your name, this would set the precedent for other people thinking something like this: "I have created a theme for Bibliogram... Hmm, how should I name it? Let's look at the other names... Ohh, this one is named after its creator, @cloudrac3r . Therefore I will name my new theme after myself!"

So in the end you are right, maybe we should refrain from using names...

**Comment by mendel5** [comment]
And btw: I think we should add the word "theme" at the end of each theme. How about this:
* Vanilla theme (classic)
* Vanilla sky theme (classic blue)

**Comment by cloudrac3r** [comment]
> I thought that you as a creator of Bibliogram should receive the honor to have a small part in it named after you.

If I wanted my name in it I would name the entire thing "Cadence Bibliogram".

> I think we should add the word "theme" at the end of each theme.

I disagree. It's redundant. We know it's a theme because it's in the theme dropdown menu. There's no need to write theme again.

**Comment by mendel5** [comment]
> If I wanted my name in it I would name the entire thing "Cadence Bibliogram".
That's right.

> We know it's a theme because it's in the theme dropdown menu.
Ok

**Comment by mendel5** [comment]
> If I wanted my name in it I would name the entire thing "Cadence Bibliogram".

That's right.

> We know it's a theme because it's in the theme dropdown menu.

Ok

**Comment by cloudrac3r** [comment]
The themes are now called "Vanilla sard" and "Vanilla sky". Re-open if you still have concerns.

**Comment by mendel5** [comment]
Thanks!
