### ISSUE TITLE
How to develop Bibliogram

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#65]
Hi @cloudrac3r ,

to make sure I can help to enhance Bibliogram more efficiently, I would like to ask you some questions about how you develop Bibliogram.

1. Which operating system do you use (e.g. Windows, OS X, Linux)?
2. Which IDE do you use?
3. Are there any other tools, programs, etc. that you recommend or that would help me?

Thanks!

**Comment by cloudrac3r** [comment]
I love to chat, but such chats would be better placed in the Matrix chatroom — join https://matrix.to/#/#bibliogram:matrix.org .

**Comment by mendel5** [comment]
Ok

**Comment by mendel5** [comment]
Btw I am now using Linux and Visual Studio Code. Works like a charm!
