### ISSUE TITLE
Broken link in bio

### ISSUE THREAD

**Issue by B0pol** [cloudrac3r/bibliogram#66]
https://bibliogram.art/u/sutihonova_
The gmail link is broken, it's considered as a link to gmail.com user on instagram.

Edit: lol, this link is broken on github. Don't forget to add the trailing _, or copy paste it: `https://bibliogram.art/u/sutihonova_`

**Comment by cloudrac3r** [comment]
Thanks for the report.

The issue is that Bibliogram has no way of telling that @gmail.com should not be treated as a username, since it is actually perfectly valid.

Feel free to suggest solutions on how this could be addressed.

**Comment by B0pol** [comment]
On Instagram, it's not seen as a link at all. To be an @account link on Instagram, it must have nothing — or whitespace — before @account. On bibliogram, whatever is before @, it's always seen as an @account link.

**Comment by cloudrac3r** [comment]
> To be an @account link on Instagram, it must have nothing — or whitespace — before @account.

Is this really the rule? Because hashtags do _not_ require a space before them to be counted as hashtags: `#space#astronomy` becomes two working hashtags.

If you're sure that this is the correct rule then I'll try to do it.
