### ISSUE TITLE
Add instances list

### ISSUE THREAD

**Issue by Booteille** [cloudrac3r/bibliogram#7]
Following Invidious and Nitter, and since this is kinda the purpose of Bibliogram, that would be great to have an instance list somewhere (I could not get to the wiki to try to add it myself).

I plan to use it in [Invidition](https://codeberg.org/Booteille/Invidition).

**Comment by cloudrac3r** [comment]
There is now an editable instance list on the wiki, but I will leave this open so I can investigate displaying other instances on the front page as well as providing an API.

**Comment by Booteille** [comment]
I would love to have an API, yup. Since I would like to avoid to make any call to github from Invidition to retrieve instances list. (That's why I didn't implement it for Nitter)

**Comment by cloudrac3r** [comment]
The instance list wiki page is now linked on the homepage, and there is now the API endpoint `/api/instances` which gets data from the wiki page and presents it as JSON (503 if the page can't be parsed). Closing as complete, but re-open if you want more features!
