### ISSUE TITLE
Add p2p for videos

### ISSUE THREAD

**Issue by wuniversales** [cloudrac3r/bibliogram#70]
I think it would be nice to add p2p for videos, to avoid cluttering the server, and add some decentralization.
I leave here the project that I would like to be integrated.
https://github.com/Novage/p2p-media-loader
Cheers

**Comment by cloudrac3r** [comment]
Seems interesting, but currently the server can keep up fine and I have more important features to add.

I'll keep this in mind and consider reviewing it in the future.

**Comment by mendel5** [comment]
Can you add the "wontfix" tag?
