### ISSUE TITLE
Make Redirector friendly 

### ISSUE THREAD

**Issue by angriness-sleek** [cloudrac3r/bibliogram#71]
Using twitter to Nitter and youtube to invidious works by setting a [redirect](https://addons.mozilla.org/en-US/android/addon/redirector/) for every twitter and youtube link, but I cannot set the an Instagram to bibliogram link. Take this example:
https://www.instagram.com/elonmusk/
to redirect that to bibliogram, I will need a query which looks like:
![IMG_20200602_022313_715](https://user-images.githubusercontent.com/62484249/83453392-f3519780-a449-11ea-8e8e-efff6c7c1afb.jpg)
But if I want to redirect a post, which is in format of: https://www.instagram.com/p/CA45UMWh8ci/
The redirect would look like: 
![IMG_20200602_022556_155](https://user-images.githubusercontent.com/62484249/83453627-5ba07900-a44a-11ea-930a-0cce745219b2.jpg)
Notice that I cannot make one redirect since I have to add /u/ in the links for an ig profile, which I have to hardcode in the redirect and then add the remaining part of the link through a query, which allows me to not be able to redirect ig post pages through it since the redirected link will become /u/p/
For the same reason I cant setup different redirects for post and profiles, since I cannot check if the URL contains a /p/ and is a post URL in the redirect for the profile as shown in first pic.
These alternative frontends - nitter and invidious work since I can redirect each of them I open from anywhere - a random tweet from reddit, a youtube link from a friend, from their twitter or youtube URLs to alternative frontend URLs, if I can't use bibliogram as such, it would largely be useless.

The simplest visible solution seems to not remove /u/ from the website and keep the format exactly like Instagram's.

**Comment by cloudrac3r** [comment]
Thanks for the extensive explanation and screenshots, but this has already been discussed in #54. Please read through all the comments on that, which should answer your questions about why made the decision to add /u/.

It _is_ possible to do this in Redirector with some more advanced regular expressions, but I suggest you install the Privacy Redirect extension instead, which will handle all of this for you.

**Comment by angriness-sleek** [comment]
Nevermind, there was always a way to do this if I had looked in the 'Advanced Options' and exclude url
![IMG_20200618_165602_801](https://user-images.githubusercontent.com/62484249/85014883-98f94c00-b156-11ea-96d3-aeff63141b64.jpg)
