### ISSUE TITLE
Private accounts produce 503 instance blocked

### ISSUE THREAD

**Issue by B0pol** [cloudrac3r/bibliogram#73]
They shouldn't. We should get bio, profile picture, sub count, publication count … and bibliogram should also say that the account is private.

**Comment by cloudrac3r** [comment]
Link to the profile that you used?

**Comment by AdKiller** [comment]
All profiles result in "503 Blocked by Instagram"

Must be related to this: https://arstechnica.com/tech-policy/2020/06/instagram-just-threw-users-of-its-embedding-api-under-the-bus/

**Comment by B0pol** [comment]
No, it's just temporary. I've tried with a public one few minutes ago, it worked.

@cloudrac3r I'll try to find another one not related to me

**Comment by cloudrac3r** [comment]
You can send me a link to the account privately if you want - check my github profile for my email address and website. It's not possible for me to read its posts, so I can't do any harm if you send me the link.

**Comment by B0pol** [comment]
I found another one: https://instagram.com/vicbetis/

**Comment by cloudrac3r** [comment]
Yeah, trying to visit it on bibliogram.art doesn't work because bibliogram.art is blocked. What's new?

**Comment by B0pol** [comment]
I've tried like with multiple instances, different hours and different days it never worked. In the same time other public account were working.
Turns out it works when I hosted bibliogram locally, this is super weird but ok

**Comment by cloudrac3r** [comment]
There's some docs here that I ought to link to on the blocked page. https://github.com/cloudrac3r/bibliogram/wiki/Rate-limits

**Comment by cloudrac3r** [comment]
> Must be related to this: https://arstechnica.com/tech-policy/2020/06/instagram-just-threw-users-of-its-embedding-api-under-the-bus/

@AdKiller - it is NOT related to that at all, your link refers to varying legal interpretations of the terms of service of an API that I don't even use. It MAY be related to [this rumor from Instaloader,](https://github.com/instaloader/instaloader/issues/654#issuecomment-637640251) but I'm giving this some time to settle before I seriously investigate what is happening, what it means, and if I can avoid it. Please don't discuss that linked Instaloader comment in this issue thread.
