### ISSUE TITLE
Docker image?

### ISSUE THREAD

**Issue by karan** [cloudrac3r/bibliogram#74]
It would be nice to provide an official docker image to run an instance in a multi-tenant environment.

**Comment by cloudrac3r** [comment]
It _would_ be nice, but I have no idea how docker works. If you do, please do create something!

**Comment by Perflyst** [comment]
I am using the following Dockerfile at the moment
```
FROM node:12.13.0-alpine

RUN apk add --no-cache git python make g++
RUN cd /opt && git clone --depth=1 https://github.com/cloudrac3r/bibliogram.git
RUN rm -rf /opt/bibliogram/.git
RUN cd /opt/bibliogram && npm install --no-optional

RUN ln -sf /opt/bibliogram/config.js /config.js

WORKDIR /opt/bibliogram/src/site

EXPOSE 10407

CMD [ "node", "server.js" ]
```

This can probably still be optimized

**Comment by cloudrac3r** [comment]
How does the ln -s config part work, what does that do?

**Comment by Perflyst** [comment]
It is for simpler config mapping. `docker run -v ./config.js:/config.js bibliogram` instead of `docker run -v ./config.js:/opt/bibliogram/config.js bibliogram`

**Comment by karan** [comment]
Thank you - that container worked great (slow to build but I don't expect anything else from node :) ).

**Comment by karan** [comment]
Closing in favor of #81
