### ISSUE TITLE
Why not to deploy to heroku

### ISSUE THREAD

**Issue by sale2000** [cloudrac3r/bibliogram#75]
> You can also deploy on Heroku, though I personally would not recommend this. Get started with Heroku.

Why do you not recommend?

I did deploy it at Heroku. It deploys but I get the typical error.

> 503
> Blocked by Instagram
> 
> Instagram is refusing to provide data to this server. Try again later to see if the block has been lifted.
> This error has been cached. The internal cache will expire in minutes.

This instance of heroku is not even public that it is overloaded. Any other suggestions.

**Comment by cloudrac3r** [comment]
Heroku's filesystem is ephemeral. Bibliogram saves data to the filesystem. When your dyno is restarted, you'll lose the user cache and saved settings. Compatibility with Heroku Postgres is not something I will be working on soon.

Instagram has recently changed their blocking policies which seem to affect cloud servers. I will write a wiki article when I have more information about what is happening. You can try running an assistant on a home IP to provide data, see the wiki for more information about assistants.

**Comment by cloudrac3r** [comment]
I will add notes about Heroku's ephemeral filesystem to the documentation soon.
