### ISSUE TITLE
Vulnerablity?

### ISSUE THREAD

**Issue by FireMasterK** [cloudrac3r/bibliogram#82]
The code in https://github.com/cloudrac3r/bibliogram/blob/7bd43ca857a60a177e0dc3168744fc2c9670fa88/src/site/api/proxy.js#L24 is used to verify whether bibliogram should proxy the url or not.
The check only checks if the url hostname ends with `cdninstagram.com` or `fbcdn.net`.

Could this mean that an attacker could register a domain such as `testcdninstagram.com` to get the IP of a bibliogram instance behind a load balancer / cloudflare?

Thanks

**Comment by cloudrac3r** [comment]
Nice find! This will be fixed tomorrow.

**Comment by cloudrac3r** [comment]
Should be fixed in 6e1e5e69968224511cc48c87a57a7268540b27e7, let me know if there are still problems here.
