### ISSUE TITLE
Readable message when IP blocked in shell

### ISSUE THREAD

**Issue by FireMasterK** [cloudrac3r/bibliogram#83]
Currently, when the user is blocked and they run the shell script, they get an error message in json like:
{"status":"fail","version":"1.0","generatedAt":redacted,"message":"These required POST body parameters were missing: user_id","fields":["bp:user_id"],"identifier":"MISSING_REQUIRED_PARAMETER...

This error message has no indication that the user IP is blocked by instagram.

**Comment by cloudrac3r** [comment]
The script has been updated to show a better error message as of 36530e5db4ed3ec979afe5578a37a315afe54683.
