### ISSUE TITLE
navigation on profiles with massive amounts of posts

### ISSUE THREAD

**Issue by guser-sudo** [cloudrac3r/bibliogram#87]
If profiles have thousands of posts, what's the suggested way to navigate them?
Maybe I want to start from the oldest post or in the middle or whatever.
I could use pages and navigate directly to e.g. page 100. However this takes a long time. Does this mean that bibliogram actually loads all pages (and pictures?) from 1 to 100 which would be a waste of traffic because I would only look at a few pages next to 100.
Also there's a _bug_: If one visits high page numbers a few times, bibliogram starts showing 2 consecutive pages with the same content. Therefore you end up with even more pages to navigate than necessary.

**Comment by cloudrac3r** [comment]
Instagram does not provide an API to get a post at a specific point, and it does not provide an API to get a post at the bottom. All you can do is get either the first page, or the page that comes after an already known timeline entry.

Yes, Bibliogram will load all pages along the way if you navigate directly with ?page=100. Please don't do this.

> bibliogram starts showing 2 consecutive pages with the same content

Does this happen if you open the same profile in multiple tabs at the same time, or can you make it happen when only loading the profile page once in one tab on once device?

**Comment by FireMasterK** [comment]
> Instagram does not provide an API to get a post at a specific point, and it does not provide an API to get a post at the bottom. All you can do is get either the first page, or the page that comes after an already known timeline entry.
> 
> Yes, Bibliogram will load all pages along the way if you navigate directly with ?page=100. Please don't do this.
Why not add something to prevent this from happening? Maybe if the previous pages haven't loaded, throw an error of some sort.

This could potentially used to DOS bibliogram instances by an attacker.

**Comment by guser-sudo** [comment]
I always open the profile in one tab and select the posts I want to see which are opened each in their own tab. Should I do that differently?

**Comment by cloudrac3r** [comment]
> I always open the profile in one tab and select the posts I want to see which are opened each in their own tab. Should I do that differently?

That sounds fine. Weird that you have issues with that. I do not know how to reproduce the bug. Let me know if you find a way to consistently load duplicate pages.

**Comment by cloudrac3r** [comment]
> This could potentially used to DOS bibliogram instances by an attacker.

It _could,_ but if that was prevented and somebody really wanted to spam Bibliogram with requests, it's as simple as:

    set i 1; while true; curl "https://bibliogram.art/u/instagram?page=$i"; set i (math $i + 1); end

Or simply picking up a cat and having it sit on Page Down, End, or Space on the keyboard. If a cat is not available, a weighted object would do the trick.

There's no open issue for it at the moment, but at some point each account or IP will have a request quota to Bibliogram in a certain time frame, which should make casual spammers ineffective.

**Comment by cloudrac3r** [comment]
I'm marking this as a question. If you'd like the duplicate pages bug reviewed, please find a way to reproduce it, and then open a new issue for it.

> (That sounds fine. Weird that you have issues with that. I do not know how to reproduce the bug. Let me know if you find a way to consistently load duplicate pages.)
