### ISSUE TITLE
one step command install on a raspberrypi

### ISSUE THREAD

**Issue by sale2000** [cloudrac3r/bibliogram#88]
I am just wondering if anyone could make a 'bash shell script' for automated install on a raspberry pi like the Pi-hole project.
This would help even 'a bit geeks' to DIY. Many thanks.

https://github.com/pi-hole/pi-hole/#one-step-automated-install

**Comment by cloudrac3r** [comment]
I'm actually experimenting with this now. Which model of Pi do you have? I have all of them except for Pi 4.

**Comment by cloudrac3r** [comment]
Ah, I misunderstood this at first. There is actually an automated script to install and run Bibliogram and keep it up to date, but it runs in fish shell, not bash. I don't know if fish is in the raspberry pi repos. If it's not, I can make a prebuilt that downloads automatically.

It's not quite one line to install it, you'll need to install fish somehow, clone the repo, and then execute run.fish.

It's currently untested on raspberry pi, but I hope to test it soon.

https://github.com/cloudrac3r/bibliogram-updater

**Comment by sale2000** [comment]
A quick search shows that `fish` does work in rpi. (I do not have rpi4 either). 
My idea was as follows:

Install bibliogram in rpi.
Install zerotier (SDN) then we get extra ip address (like 10.147.18.1) non internet -routable. 
I am not an expert in webserver configs but I thought add this to bibliogram webserver somehow.
Then, if your client (laptop) has zerotier, then you can to http://10.147.18.1 to access bibliogram.

**Comment by cloudrac3r** [comment]
I don't think setting up zerotier is an appropriate job of the Bibliogram installation script. If you already have it installed, then you can enter `http://0.0.0.0:10407`, replacing `0.0.0.0` with the zerotier IP you got, when asked what URL people should use to visit.

You can try the script on your raspberry pi now:

    wget https://raw.githubusercontent.com/cloudrac3r/bibliogram-updater/master/.clone.sh -O clone.sh
    bash clone.sh

As far as I know, this cannot be combined into a single `curl | bash` because then bash can't take input from the keyboard, so you'll have to make it those two commands. This should install fish, git, and node automatically, which is all the extra dependencies that Bibliogram needs on raspbian lite.

Running npm install takes a _really_ long time. Get your snacks.

**Comment by sale2000** [comment]
I tried the `./run.fish` and 'clone.sh'

```
root@bionic-bibliogram ~/bibliogram-updater# ./run.fish

====================================
Welcome to the Bibliogram installer.
Please pay attention as you will be
asked to make choices.
====================================

node not found in path.
Download the node executable now? It will not be installed system-wide.
The Linux x64 version will be downloaded.
[press Enter to continue, or Ctrl-C to quit]
node.tar.xz                         100%[================================================================>]  19.87M  47.7MB/s    in 0.4s
2020-06-22 12:44:49 URL:https://nodejs.org/dist/v14.4.0/node-v14.4.0-linux-x64.tar.xz [20837612/20837612] -> "node.tar.xz" [1]
Extracting... done.

set: Unknown option '-a'
./install.fish (line 37):
        set -a PATH $PWD/$node_folder/bin
        ^

       setset - display and change shell variables.
        -


```

**Comment by sale2000** [comment]
> I don't think setting up zerotier is an appropriate job 

Absolutely not. I just meant that it would be 'suggestion' one could add to wiki. So that normal users do not need to port forward or run public instance.

**Comment by cloudrac3r** [comment]
> set: Unknown option '-a'

That's weird. What's your `fish --version` ?

**Comment by sale2000** [comment]
```
root@bionic-bibliogram ~# fish --version
fish, version 2.7.1

```

**Comment by cloudrac3r** [comment]
My pi has fish 3.0.2 and the script works there. I'm just using the latest raspbian lite image. Can you post a link to ubuntu ppa fish 3?

**Comment by sale2000** [comment]
Since my pi was not working, I went ubuntu/bionic but installed with:

https://launchpad.net/~fish-shell/+archive/ubuntu/release-3


BTW did manage to install everything. Still failing. 
```
root@bionic-bibliogram ~/bibliogram-updater (master)# cd bibliogram/
root@bionic-bibliogram ~/b/bibliogram (master)# ls
Dockerfile  Procfile   app.json  config.js  docker-compose.yml  node_modules/      package.json  src/
LICENSE     README.md  art/      db/        jsconfig.json       package-lock.json  scripts/      test/
root@bionic-bibliogram ~/b/bibliogram (master)# npm run start
(node:2714) UnhandledPromiseRejectionWarning: Error: Cannot find module 'better-sqlite3'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/bibliogram-updater/bibliogram/src/lib/db.js:1:78)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
(node:2714) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:2714) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
If I go to http://10.147.19.159:10408 it says  Malformed URI

BTW, during installation why are there 2 places to give port number: 

```
What URL will people visit to access your instance?
(example for public internet: https://bibliogram.art)
(example for your LAN: http://10.137.217.45:10407)
[type!] > http://10.147.19.159:10407

What port should Bibliogram's webserver listen on?
You cannot use ports below 1024.
[type!] > 10408


```
Should I give the same port number in both places?

**Comment by cloudrac3r** [comment]
Yes, you should give the same port number.

The first one is the port number that visitors should use. The second one is the one that Bibliogram should actually listen on. If you're using nginx to provide HTTPS, like all current public instances are, then nginx listens on ports 80 and 443 and sends requests to whatever port Bibliogram is internally listening on. In this case the ports will be different but in cases where you're connecting to Bibliogram directly, they should be the same.

**Comment by cloudrac3r** [comment]
Let me know if you still have problems with this. The updater script works on my Pi 2 using fish from the default repos on the current raspbian lite image.

**Comment by cloudrac3r** [comment]
Closing this because it should be solved by bibliogram-updater, and because it hasn't been commented on in 3 weeks.
