### ISSUE TITLE
Blocked profiles affect RSS

### ISSUE THREAD

**Issue by webdevjmcom** [cloudrac3r/bibliogram#89]
The RSS doesn't update when the profile is blocked

**Comment by cloudrac3r** [comment]
Can you please describe the issue in more detail? Which instance are you using RSS from?

**Comment by webdevjmcom** [comment]
I'm using https://bibliogram.webdevjm.com
When I refresh my feed reader nothing happens. Then I check the profile and it says it's blocked so I unblock it and then it works immediately after.

Jun 21, 2020 22:30:54 Cadence Ember <notifications@github.com>:

**Comment by cloudrac3r** [comment]
Yeah, that's what happens when a profile is blocked: it doesn't work.

After you unblock it once the feed should work from then on.

**Comment by webdevjmcom** [comment]
I realized that some profiles get block again after I unblock them. I've never monitored it so I don't know how long it takes

Jun 22, 2020 01:17:47 Cadence Ember <notifications@github.com>:

**Comment by cloudrac3r** [comment]
If this is your instance, make sure that the database is never being reset. Docker, Heroku, and others will do that.

**Comment by webdevjmcom** [comment]
I used nodejs to run it. Is that included?

Jun 22, 2020 01:21:39 Cadence Ember <notifications@github.com>:

**Comment by cloudrac3r** [comment]
Hmm, that _should_ work. Unblocked profiles are saved to db/bibliogram.db. If this file is ever deleted or moved then all profiles will have to be unblocked again.

What is the exact command that you are using to start it, and what is the output of `node --version` ?

**Comment by webdevjmcom** [comment]
The version is v12.18.1 and I used "npm start"

Jun 22, 2020 01:26:15 Cadence Ember <notifications@github.com>:

**Comment by cloudrac3r** [comment]
That sounds like it should work fine. Please tell me a profile that works at the moment, and if the same profile breaks in the future, we can come back and talk about this in more detail.

**Comment by webdevjmcom** [comment]
I just unblocked https://bibliogram.webdevjm.com/u/alux/ I'll watch it to see if it gets blocked again

Jun 22, 2020 01:33:19 Cadence Ember <notifications@github.com>:

**Comment by cloudrac3r** [comment]
Neat. If it's blocked in future, _do not unblock it again,_ because I'll need to examine the situation for myself.

**Comment by webdevjmcom** [comment]
Ok, I'll let you know

Jun 22, 2020 01:41:29 Cadence Ember <notifications@github.com>:
