### ISSUE TITLE
incorrect onion site link

### ISSUE THREAD

**Issue by webdevjmcom** [cloudrac3r/bibliogram#91]
I added the onion_location to my config file on bibliogram.webdevjm.com
The address is myuurkl22xo3jwi733kacy6xacgbzzl3kp7u4ovp7sf5nlt7xjvpv2qd.onion
The address that shows up in the link "Onion site available" is bibliogram.webdevjm.com/myuurkl22xo3jwi733kacy6xacgbzzl3kp7u4ovp7sf5nlt7xjvpv2qd.onion.
I'm also wondering if the onion address should be a link or just be displayed because some people might accidentally open it in a regular browser that way.

**Comment by cloudrac3r** [comment]
you must prefix the onion_location with `http://` as in the example.
