### ISSUE TITLE
Allow color change of "Loading..." notice through themes

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#92]
This issue is related to this comment: https://github.com/cloudrac3r/bibliogram/issues/27#issuecomment-636578879

An option would be added so that it is possible to change the color of the "Loading..." notice trough a theme. Currently it's always green, which is not fitting for some themes.

![bibliogram-loading](https://user-images.githubusercontent.com/60322520/85928274-066e5080-b8ac-11ea-9b60-2f564c963dc5.png)

Btw maybe this option has already been implemented but I haven't seen it yet.

**Comment by cloudrac3r** [comment]
The button now matches the main scheme of the selected theme as of eb0633e0.

**Comment by mendel5** [comment]
Thanks!
