### ISSUE TITLE
Images in the timeline are only partially loaded

### ISSUE THREAD

**Issue by mendel5** [cloudrac3r/bibliogram#93]
Some days ago I came across a bug, where images in the timeline are only loaded partially.

Here is a screenshot of https://bibliogram.art/u/justinbieber :
![bibliogram-justinbieber](https://user-images.githubusercontent.com/60322520/85928468-82b56380-b8ad-11ea-9f80-b30d74b2fc30.png)

At the time of writing this I am only able to reproduce this on https://bibliogram.13ad.de/u/parishilton . In Firefox it looks like this:
![bibliogram-parishilton](https://user-images.githubusercontent.com/60322520/85928490-9a8ce780-b8ad-11ea-97a3-eb221c4c7c32.png)

In Chromium it looks like this:
![bibliogram-parishilton-chromium](https://user-images.githubusercontent.com/60322520/85928524-d162fd80-b8ad-11ea-800b-2b353dfd1bc6.png)

I am not sure what causes this.

**Comment by cloudrac3r** [comment]
Loads for me. Maybe your internet connection was having problems, maybe the site was having problems.
