### ISSUE TITLE
Deleted accounts throw a 500 error

### ISSUE THREAD

**Issue by guser-sudo** [cloudrac3r/bibliogram#95]
Accounts which no longer exist on Instagram show this:
```
           ◸―――――――――――――――――――――――――――――――――――――◹
     ···<  |        500. That's an error.        |  >···
           ◺―――――――――――――――――――――――――――――――――――――◿


 ╱  Are you visiting this website? Not sure what's going on?  ╲
 ╲             You might want to come back later.             ╱



TypeError: Cannot read property 'edge_owner_to_timeline_media' of null
    at /home/cloud/bupdate/bibliogram/src/lib/collectors.js:278:36
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/cloud/bupdate/bibliogram/src/lib/collectors.js:253:17
```

**Comment by cloudrac3r** [comment]
I don't have a deleted account to test with. Give me the username.

**Comment by guser-sudo** [comment]
[example account](https://bibliogram.art/u/rapoport)

**Comment by cloudrac3r** [comment]
Fixed. Thank you for the example account.

Note for sysadmins: accounts that are requested and detected as deleted are then removed from the database, partly for data privacy reasons, partly because someone else might claim the username in the future.

**Comment by guser-sudo** [comment]
@cloudrac3r
After some weeks of testing I can now say this isn't properly fixed. E.g. accounts with 0 posts won't be recognized as being deleted.

**Comment by cloudrac3r** [comment]
Once again you'll need to provide an example account for me to work with.

Please open a new issue on sourcehut: https://todo.sr.ht/~cadence/bibliogram-issues
