### ISSUE TITLE
Bibliogram on Android 

### ISSUE THREAD

**Issue by Xarchuser** [cloudrac3r/bibliogram#96]
I was able to install Bibliogram on Android using Termux and even surf on some Instagram accounts using 0.0.0.0:10407 but the images are broken, I can't see anything. I think there's a problem with libvips. Maybe u could help me, I couldn't figure out how to install libvips on termux, I'm not good compiling it 

```
$:npm start
 Server started
(node:29369) UnhandledPromiseRejectionWarning: Error: 'linux-armv7' binaries cannot be used on the 'android-armv7' platform. Please remove the 'node_modules/sharp' directory and run 'npm install' on the 'android-armv7' platform.
    at Object.hasVendoredLibvips/data/data/com.termux/files/home/bibliogram/node_modules/sharp/lib/libvips.js:68:13)
    at Object.<anonymous> (/data/data/com.termux/files/home/bibliogram/node_modules/sharp/lib/constructor.js:7:22)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:994:10)
    at Module.load (internal/modules/cjs/loader.js:813:32)
    at Function.Module._load (internal/modules/cjs/loader.js:725:14)
    at Module.require (internal/modules/cjs/loader.js:850:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/data/data/com.termux/files/home/bibliogram/node_modules/sharp/lib/index.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:958:30)
(node:29369) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29369) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ ] [211446] [CMP] Compiled sass/includes/_dimensions.sass
[ ] [211446] [CMP] Compiled sass/includes/_forms.sass
[ ] [211446] [CMP] Compiled sass/themes/_blue.scss
[ ] [211446] [CMP] Compiled sass/themes/_classic.scss
[ ] [211446] [CMP] Compiled sass/themes/_discord.scss
[ ] [211446] [CMP] Compiled sass/themes/_pitchblack.scss
[ ] [211447] [CMP] Compiled sass/themes/_pussthecat.org-v2.scss
[ ] [211447] [CMP] Compiled sass/themes/_pussthecat.org.scss
[ ] [211447] [CMP] Compiled sass/blue.sass
[ ] [211448] [CMP] Compiled sass/classic.sass
[ ] [211448] [CMP] Compiled sass/discord.sass
[ ] [211448] [CMP] Compiled sass/includes/_main.sass
[ ] [211449] [CMP] Compiled sass/pitchblack.sass
[ ] [211449] [CMP] Compiled sass/pussthecat.org-v2.sass
[ ] [211449] [CMP] Compiled sass/pussthecat.org.sass
[.] REPL started
b) [ ] [211510] [INC] /
[ ] [211510] [API] / = /
[ ] [211513] [INC] /u/programapanico
[ ] [211513] [API] /u/programapanico = /u/([\w.]*[\w])(/channel)?
      -> [OUT-NF ] https://www.instagram.com/graphql/query/?query_hash=e769aa130647d2354c40ea6a439bfc08&variables=%7B%22id%22%3A%22293223772%22%2C%22first%22%3A12%2C%22after%22%3A%22%22%7D
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404
[ ] [211516] [INC] /404
[ ] [211516] [API] /404 = /404

```

**Comment by cloudrac3r** [comment]
LMAO

try `pkg install build-essential` then `npm install` then start it again.

**Comment by cloudrac3r** [comment]
if you copied the installation from your computer to your phone rather than originally cloning it on your phone, you'll need to `rm -rf node_modules` before doing any of that.

**Comment by Xarchuser** [comment]
> LMAO
> 
> try `pkg install build-essential` then `npm install` then start it again.

$:npm install                            
make: Entering directory '/data/data/com.termux/files/home/bibliogram/node_modules/integer/build'                                             CXX(target) Release/obj.target/integer/src/integer.o
  SOLINK_MODULE(target) Release/obj.target/integer.node               clang-9: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]                                                 COPY Release/integer.node
make: Leaving directory '/data/data/com.termux/files/home/bibliogram/node_modules/integer/build'                                            make: Entering directory '/data/data/com.termux/files/home/bibliogram/node_modules/better-sqlite3/build'                                      TOUCH b857c92884e9598d609f6be182a2595df7a8e00f.intermediate           ACTION deps_sqlite3_gyp_locate_sqlite3_target_extract_sqlite3 b857c92884e9598d609f6be182a2595df7a8e00f.intermediate                         TOUCH Release/obj.target/deps/locate_sqlite3.stamp                    CC(target) Release/obj.target/sqlite3/gen/sqlite3/sqlite3.o         warning: unknown warning option '-Wno-cast-function-type'; did you
      mean '-Wno-bad-function-cast'? [-Wunknown-warning-option]       1 warning generated.
  AR(target) Release/obj.target/deps/sqlite3.a                          COPY Release/sqlite3.a
  CXX(target) Release/obj.target/better_sqlite3/src/better_sqlite3.o    SOLINK_MODULE(target) Release/obj.target/better_sqlite3.node        clang-9: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]                                                 COPY Release/better_sqlite3.node
  CC(target) Release/obj.target/test_extension/deps/test_extension.o    SOLINK_MODULE(target) Release/obj.target/test_extension.node
clang-9: warning: argument unused during compilation: '-pie' [-Wunused-command-line-argument]
  COPY Release/test_extension.node                                    rm b857c92884e9598d609f6be182a2595df7a8e00f.intermediate              make: Leaving directory '/data/data/com.termux/files/home/bibliogram/node_modules/better-sqlite3/build'                                     info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.9.1/libvips-8.9.1-android-armv7.tar.gz                  ERR! sharp Prebuilt libvips 8.9.1 binaries are not yet available for android-armv7                                                          info sharp Attempting to build from source via node-gyp but this may fail due to the above error                                            info sharp Please see https://sharp.pixelplumbing.com/install for required dependencies                                                     make: Entering directory '/data/data/com.termux/files/home/bibliogram/node_modules/sharp/build'                                               CC(target) Release/obj.target/nothing/../node-addon-api/nothing.o     AR(target) Release/obj.target/../node-addon-api/nothing.a             COPY Release/nothing.a                                                TOUCH Release/obj.target/libvips-cpp.stamp                            CXX(target) Release/obj.target/sharp/src/common.o                   warning: unknown warning option '-Wno-psabi'                                [-Wunknown-warning-option]                                      ../src/common.cc:23:10: fatal error: 'vips/vips8' file not found      #include <vips/vips8>
         ^~~~~~~~~~~~                                                 1 warning and 1 error generated.
make: *** [sharp.target.mk:129: Release/obj.target/sharp/src/common.o] Error 1
make: Leaving directory '/data/data/com.termux/files/home/bibliogram/node_modules/sharp/build'
```

**Comment by Xarchuser** [comment]
> if you copied the installation from your computer to your phone rather than originally cloning it on your phone, you'll need to `rm -rf node_modules` before doing any of that.

Nope I just did clone your repo and followed that instructions

**Comment by Xarchuser** [comment]
I installed with `npm install --platform=linux`
Unfortunately photos doesn't load :(

**Comment by cloudrac3r** [comment]
You'll need to build vips from source and let sharp know about it using information from these pages:

https://libvips.github.io/libvips/install.html section: building from source 

https://sharp.pixelplumbing.com/install#custom-libvips section: custom libvips

**Comment by cloudrac3r** [comment]
Alternatively, try the somewhat out of date "gm" branch. You'll need to `npm install` again.

**Comment by Xarchuser** [comment]
> Alternatively, try the somewhat out of date "gm" branch. You'll need to `npm install` again.

This way almost worked 100%, installation got no errors, and at least the Instagram profile pics are showing up and now I can see Instagram's post images, however the main page, I mean the time-line the photos are still broken. I'm gonna try to compile vips from source later. Anyway thank you.

**Comment by cloudrac3r** [comment]
Closing this since it's not a problem report or feature request, and it's been 2 weeks since the last post.

**Comment by fossdd** [comment]
You may also are interested in https://f-droid.org/en/packages/me.austinhuang.instagrabber/.
